import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

export const ExportService = {
    /**
     * Export a DOM element as a PNG image.
     * @param elementId The ID of the DOM element to capture.
     * @param fileName The name of the file to download (without extension).
     */
    async downloadPNG(elementId: string, fileName: string) {
        try {
            const element = document.getElementById(elementId);
            if (!element) throw new Error(`Element with ID '${elementId}' not found`);

            const canvas = await html2canvas(element, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
            const dataUrl = canvas.toDataURL('image/png');

            const link = document.createElement('a');
            link.href = dataUrl;
            link.download = `${fileName}.png`;
            link.click();
        } catch (error) {
            console.error('Export PNG failed:', error);
            throw error;
        }
    },

    /**
     * Export a DOM element as a PDF document.
     * @param elementId The ID of the DOM element to capture.
     * @param fileName The name of the file to download.
     */
    async downloadPDF(elementId: string, fileName: string) {
        try {
            const element = document.getElementById(elementId);
            if (!element) throw new Error(`Element with ID '${elementId}' not found`);

            const canvas = await html2canvas(element, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
            const imgData = canvas.toDataURL('image/png');

            // A4 dimensions in mm
            const pdfWidth = 210;
            const pdfHeight = 297;

            const imgProps = canvas.width / canvas.height;
            const printWidth = pdfWidth - 20; // 10mm margin each side
            const printHeight = printWidth / imgProps;

            const pdf = new jsPDF('p', 'mm', 'a4');

            // Header
            pdf.setFontSize(14);
            pdf.text(fileName, 10, 15);

            pdf.setFontSize(9);
            pdf.setTextColor(100);
            pdf.text(`Generated by InsightEngine - ${new Date().toLocaleDateString()}`, 10, 22);

            // Image
            pdf.addImage(imgData, 'PNG', 10, 30, printWidth, printHeight);

            // Footer
            pdf.setFontSize(8);
            pdf.setTextColor(150);
            pdf.text('Confidential - Internal Use Only', 10, 290);

            pdf.save(`${fileName}.pdf`);
        } catch (error) {
            console.error('Export PDF failed:', error);
            throw error;
        }
    },

    /**
     * Export data array to CSV.
     * @param data Array of objects.
     * @param fileName File name.
     */
    exportDataToCSV(data: any[], fileName: string) {
        if (!data || !data.length) return;

        const headers = Object.keys(data[0]);
        const csvContent = [
            headers.join(','), // Header row
            ...data.map(row => headers.map(header => {
                const val = row[header];
                // Handle strings with commas or newlines
                if (typeof val === 'string' && (val.includes(',') || val.includes('\n'))) {
                    return `"${val.replace(/"/g, '""')}"`;
                }
                return val;
            }).join(','))
        ].join('\n');

        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement('a');
        if (link.download !== undefined) {
            const url = URL.createObjectURL(blob);
            link.setAttribute('href', url);
            link.setAttribute('download', fileName.endsWith('.csv') ? fileName : `${fileName}.csv`);
            link.style.visibility = 'hidden';
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        }
    }
};
